#!/bin/bash
# Prepared commands only. Do not run until the parent releases the root gate.
set -euo pipefail
if [[ "${QUEUE_VALIDATION_RELEASED:-}" != "1" ]]; then
  echo 'Held: requires explicit parent release and QUEUE_VALIDATION_RELEASED=1.' >&2
  exit 2
fi
here="$(cd -- "$(dirname -- "$0")" && pwd)"
sandbox="$(python3 -c 'import json,sys;print(json.load(open(sys.argv[1]))["sandbox"])' "$here/prepared.json")"
export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk-21.jdk/Contents/Home
export PATH="$JAVA_HOME/bin:$PATH"
export GOWORK=off GOMAXPROCS=2 GOMEMLIMIT=256MiB GOGC=100 TZ=UTC LC_ALL=C
out="$sandbox/validation"
mkdir "$out"
# Verify prepared runtime/compiler bytes before injecting tests or diagnostics.
python3 - "$here/prepared.json" <<'PY'
import hashlib,json,sys
from pathlib import Path
m=json.load(open(sys.argv[1]));s=Path(m['sandbox'])
for variant in ['baseline','candidate']:
 for rel,want in m['source_manifest'].items():
  if variant=='candidate' and rel=='stdjava/reference_arrays.go':want=m['candidate_file_sha256']
  assert hashlib.sha256((s/variant/rel).read_bytes()).hexdigest()==want,(variant,rel)
for rel,want in m['input_hashes'].items():assert hashlib.sha256((s/'inputs'/rel).read_bytes()).hexdigest()==want,rel
PY
for variant in baseline candidate; do
  cp "$sandbox/inputs/candidate-harness/regression_test.go.txt" "$sandbox/$variant/stdjava/performance_queue_test.go"
done
if (cd "$sandbox/baseline" && go test ./stdjava -run '^TestCandidateSmallTraversalAllocation$' -count=1) >"$out/baseline-red.log" 2>&1; then
  echo 'Expected the baseline allocation regression to fail.' >&2
  exit 1
fi
rg -q 'allocated [1-9]' "$out/baseline-red.log"
(cd "$sandbox/candidate" && go test ./stdjava -run '^TestCandidateSmallTraversalAllocation$' -count=1) >"$out/candidate-green.log" 2>&1
# Both suites include replacement/concurrency/order/overflow tests. Only the
# baseline and race runs exclude the intentional allocation expectation.
(cd "$sandbox/baseline" && go test ./stdjava -count=1 -skip '^TestCandidateSmallTraversalAllocation$') >"$out/baseline-runtime.log" 2>&1
(cd "$sandbox/candidate" && go test ./stdjava -count=1) >"$out/candidate-runtime.log" 2>&1
focus='^(TestCampaignRuntimeSQL.*|TestCampaignRuntimeBoundedOwnerMethodReferenceConsumers|TestCampaignRuntimeCanonicalOwnerInferenceEquality|TestCampaignFamilyReview08SuperclassCast|TestCampaignCanonicalFactoryAliasContracts|TestCampaignNestedGenericFactoryIdentity|TestCampaignGenericLeafRawPollutionTiming|TestCampaignGenericFamilyStorageDependencies|TestSourceDowncastRecoversCanonicalObjectView|TestCampaignNullableReferenceCasts|TestCampaignRuntimeMonitor.*)$'
for variant in baseline candidate; do
  (cd "$sandbox/$variant" && go test -race ./stdjava -count=1 -skip '^TestCandidateSmallTraversalAllocation$') >"$out/$variant-race.log" 2>&1
  (cd "$sandbox/$variant" && go test ./transpiler -run "$focus" -count=1 -timeout=15m) >"$out/$variant-round09-oracles.log" 2>&1
  cp "$sandbox/inputs/identity-harness/diagnostics.go.txt" "$sandbox/$variant/stdjava/performance_identity_diagnostics.go"
done
# One compiler produces one set of generated bytes for both runtimes.
(cd "$sandbox/baseline" && go build -o "$out/java2go" ./cmd/java2go) >"$out/compiler-build.log" 2>&1
"$out/java2go" -strict -w -output "$out/generated" "$sandbox/inputs/identity-source" >"$out/transpile.log" 2>&1
"$out/java2go" -strict -w -output "$out/semantics" "$sandbox/inputs/candidate-source" >"$out/transpile-semantics.log" 2>&1
for variant in baseline candidate; do
  for label in generated semantics; do
    app="$out/$variant-$label"
    cp -R "$out/$label" "$app"
    printf 'module perf.objectidentity\n\ngo 1.27.0\n\nrequire github.com/NickyBoy89/java2go v0.0.0\n\nreplace github.com/NickyBoy89/java2go => %s\n' "$sandbox/$variant" >"$app/go.mod"
    if [[ "$label" == generated ]]; then
      cp "$sandbox/inputs/identity-harness/counted_driver.go.txt" "$app/driver.go"
    else
      cp "$sandbox/inputs/candidate-harness/semantics_driver.go.txt" "$app/driver.go"
    fi
    (cd "$app" && go build -mod=mod -o "$out/$variant-$label-bin" .) >"$out/$variant-$label-build.log" 2>&1
  done
done
cmp "$out/baseline-generated/ObjectIdentityProbe.go" "$out/candidate-generated/ObjectIdentityProbe.go"
cmp "$out/baseline-semantics/QueueSemantics.go" "$out/candidate-semantics/QueueSemantics.go"
mkdir "$out/classes"
"$JAVA_HOME/bin/javac" --release 21 -d "$out/classes" "$sandbox/inputs/identity-source/ObjectIdentityProbe.java" "$sandbox/inputs/identity-harness/IdentityDriver.java" "$sandbox/inputs/candidate-source/QueueSemantics.java" "$sandbox/inputs/candidate-harness/SemanticsDriver.java" >"$out/javac.log" 2>&1
java=("$JAVA_HOME/bin/java" -XX:+UseSerialGC -XX:ActiveProcessorCount=2 -Xms32m -Xmx256m -cp "$out/classes")
"${java[@]}" SemanticsDriver >"$out/java-semantics.stdout" 2>"$out/java-semantics.stderr"
for variant in baseline candidate; do
  "$out/$variant-semantics-bin" >"$out/$variant-semantics.stdout" 2>"$out/$variant-semantics.stderr"
  cmp "$out/java-semantics.stdout" "$out/$variant-semantics.stdout"
done
# These are post-GC observations, not elapsed-time benchmarks.
for seed in 17 97; do
  for mode in 0 1 2; do
    order=(java baseline candidate)
    if [[ "$seed" == 97 ]]; then order=(candidate baseline java); fi
    for variant in "${order[@]}"; do
      if [[ "$variant" == java ]]; then command=("${java[@]}" IdentityDriver); else command=("$out/$variant-generated-bin"); fi
      "${command[@]}" "$seed" "$mode" >"$out/$variant-$seed-$mode.stdout" 2>"$out/$variant-$seed-$mode.stderr"
    done
    cmp "$out/java-$seed-$mode.stdout" "$out/baseline-$seed-$mode.stdout"
    cmp "$out/java-$seed-$mode.stdout" "$out/candidate-$seed-$mode.stdout"
  done
done
for variant in baseline candidate; do
  app="$out/$variant-generated"
  cp "$sandbox/inputs/identity-harness/allocation_test.go.txt" "$app/identity_allocation_test.go"
  for trial in 0 1 2; do
    (cd "$app" && go test -mod=mod -run '^TestObjectIdentityAllocations$' -count=1 -v .) >"$out/$variant-allocation-$trial.log" 2>&1
  done
done
printf 'Validation complete. Review logs and decimal-byte observations in %s\n' "$out"
