/*
 * Copyright (c) 2012, 2024, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */

/*
 * COPYRIGHT AND PERMISSION NOTICE
 *
 * Copyright (c) 1991-2022 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in https://www.unicode.org/copyright.html.
 *
 * Permission is hereby granted, free of charge, to any person obtaining
 * a copy of the Unicode data files and any associated documentation
 * (the "Data Files") or Unicode software and any associated documentation
 * (the "Software") to deal in the Data Files or Software
 * without restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, and/or sell copies of
 * the Data Files or Software, and to permit persons to whom the Data Files
 * or Software are furnished to do so, provided that either
 * (a) this copyright and permission notice appear with all copies
 * of the Data Files or Software, or
 * (b) this copyright and permission notice appear in associated
 * Documentation.
 *
 * THE DATA FILES AND SOFTWARE ARE PROVIDED "AS IS", WITHOUT WARRANTY OF
 * ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT OF THIRD PARTY RIGHTS.
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS
 * NOTICE BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL
 * DAMAGES, OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE,
 * DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
 * TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
 * PERFORMANCE OF THE DATA FILES OR SOFTWARE.
 *
 * Except as contained in this notice, the name of a copyright holder
 * shall not be used in advertising or otherwise to promote the sale,
 * use or other dealings in these Data Files or Software without prior
 * written authorization of the copyright holder.
 */

// Generated English CLDR timezone data from pinned JDK21 java.base/sun/util/resources/cldr/TimeZoneNames_en.java
// src.zip SHA256 d887da897fc0065a2532500ee92320ce3bc633ccd6c4e637304045ce5d90de43
// Only locale data is extracted; parsing/formatting is implemented separately.
package stdjava

var dateFormatEnglishZones = []dateFormatZoneData{
	{"America/Los_Angeles", [6]string{"Pacific Standard Time", "PST", "Pacific Daylight Time", "PDT", "Pacific Time", "PT"}},
	{"America/Denver", [6]string{"Mountain Standard Time", "MST", "Mountain Daylight Time", "MDT", "Mountain Time", "MT"}},
	{"America/Phoenix", [6]string{"Mountain Standard Time", "MST", "Mountain Daylight Time", "MDT", "Mountain Time", "MT"}},
	{"America/Chicago", [6]string{"Central Standard Time", "CST", "Central Daylight Time", "CDT", "Central Time", "CT"}},
	{"America/New_York", [6]string{"Eastern Standard Time", "EST", "Eastern Daylight Time", "EDT", "Eastern Time", "ET"}},
	{"America/Indianapolis", [6]string{"Eastern Standard Time", "EST", "Eastern Daylight Time", "EDT", "Eastern Time", "ET"}},
	{"Pacific/Honolulu", [6]string{"Hawaii-Aleutian Standard Time", "HST", "Hawaii-Aleutian Daylight Time", "HDT", "Hawaii-Aleutian Time", "HST"}},
	{"America/Anchorage", [6]string{"Alaska Standard Time", "AKST", "Alaska Daylight Time", "AKDT", "Alaska Time", "AKT"}},
	{"America/Halifax", [6]string{"Atlantic Standard Time", "AST", "Atlantic Daylight Time", "ADT", "Atlantic Time", "AT"}},
	{"America/Sitka", [6]string{"Alaska Standard Time", "AKST", "Alaska Daylight Time", "AKDT", "Alaska Time", "AKT"}},
	{"America/St_Johns", [6]string{"Newfoundland Standard Time", "", "Newfoundland Daylight Time", "", "Newfoundland Time", ""}},
	{"Europe/Paris", [6]string{"Central European Standard Time", "", "Central European Summer Time", "", "Central European Time", ""}},
	{"GMT", [6]string{"Greenwich Mean Time", "GMT", "", "", "", ""}},
	{"Asia/Jerusalem", [6]string{"Israel Standard Time", "", "Israel Daylight Time", "", "Israel Time", ""}},
	{"Asia/Tokyo", [6]string{"Japan Standard Time", "", "Japan Daylight Time", "", "Japan Time", ""}},
	{"Europe/Bucharest", [6]string{"Eastern European Standard Time", "", "Eastern European Summer Time", "", "Eastern European Time", ""}},
	{"Asia/Shanghai", [6]string{"China Standard Time", "", "China Daylight Time", "", "China Time", ""}},
	{"UTC", [6]string{"Coordinated Universal Time", "UTC", "", "", "", ""}},
	{"ACT", [6]string{"Australian Central Standard Time", "", "Australian Central Daylight Time", "", "Central Australia Time", ""}},
	{"AET", [6]string{"Australian Eastern Standard Time", "", "Australian Eastern Daylight Time", "", "Eastern Australia Time", ""}},
	{"ART", [6]string{"Eastern European Standard Time", "", "Eastern European Summer Time", "", "Eastern European Time", ""}},
	{"AST", [6]string{"Alaska Standard Time", "AKST", "Alaska Daylight Time", "AKDT", "Alaska Time", "AKT"}},
	{"BET", [6]string{"Brasilia Standard Time", "", "Brasilia Summer Time", "", "Brasilia Time", ""}},
	{"BST", [6]string{"Bangladesh Standard Time", "", "Bangladesh Summer Time", "", "Bangladesh Time", ""}},
	{"CAT", [6]string{"Central Africa Time", "", "", "", "", ""}},
	{"CNT", [6]string{"Newfoundland Standard Time", "", "Newfoundland Daylight Time", "", "Newfoundland Time", ""}},
	{"CST", [6]string{"Central Standard Time", "CST", "Central Daylight Time", "CDT", "Central Time", "CT"}},
	{"CTT", [6]string{"China Standard Time", "", "China Daylight Time", "", "China Time", ""}},
	{"EAT", [6]string{"East Africa Time", "", "", "", "", ""}},
	{"ECT", [6]string{"Central European Standard Time", "", "Central European Summer Time", "", "Central European Time", ""}},
	{"JST", [6]string{"Japan Standard Time", "", "Japan Daylight Time", "", "Japan Time", ""}},
	{"MIT", [6]string{"Apia Standard Time", "", "Apia Daylight Time", "", "Apia Time", ""}},
	{"NET", [6]string{"Armenia Standard Time", "", "Armenia Summer Time", "", "Armenia Time", ""}},
	{"NST", [6]string{"New Zealand Standard Time", "", "New Zealand Daylight Time", "", "New Zealand Time", ""}},
	{"PLT", [6]string{"Pakistan Standard Time", "", "Pakistan Summer Time", "", "Pakistan Time", ""}},
	{"PNT", [6]string{"Mountain Standard Time", "MST", "Mountain Daylight Time", "MDT", "Mountain Time", "MT"}},
	{"PRT", [6]string{"Atlantic Standard Time", "AST", "Atlantic Daylight Time", "ADT", "Atlantic Time", "AT"}},
	{"PST", [6]string{"Pacific Standard Time", "PST", "Pacific Daylight Time", "PDT", "Pacific Time", "PT"}},
	{"SST", [6]string{"Solomon Islands Time", "", "", "", "", ""}},
	{"CST6CDT", [6]string{"Central Standard Time", "CST", "Central Daylight Time", "CDT", "Central Time", "CT"}},
	{"EST5EDT", [6]string{"Eastern Standard Time", "EST", "Eastern Daylight Time", "EDT", "Eastern Time", "ET"}},
	{"Etc/GMT", [6]string{"Greenwich Mean Time", "GMT", "", "", "", ""}},
	{"Etc/UTC", [6]string{"Coordinated Universal Time", "UTC", "", "", "", ""}},
	{"MST7MDT", [6]string{"Mountain Standard Time", "MST", "Mountain Daylight Time", "MDT", "Mountain Time", "MT"}},
	{"PST8PDT", [6]string{"Pacific Standard Time", "PST", "Pacific Daylight Time", "PDT", "Pacific Time", "PT"}},
	{"Asia/Aden", [6]string{"Arabian Standard Time", "", "Arabian Daylight Time", "", "Arabian Time", ""}},
	{"Asia/Baku", [6]string{"Azerbaijan Standard Time", "", "Azerbaijan Summer Time", "", "Azerbaijan Time", ""}},
	{"Asia/Dili", [6]string{"East Timor Time", "", "", "", "", ""}},
	{"Asia/Gaza", [6]string{"Eastern European Standard Time", "", "Eastern European Summer Time", "", "Eastern European Time", ""}},
	{"Asia/Hovd", [6]string{"Hovd Standard Time", "", "Hovd Summer Time", "", "Hovd Time", ""}},
	{"Asia/Omsk", [6]string{"Omsk Standard Time", "", "Omsk Summer Time", "", "Omsk Time", ""}},
	{"Asia/Oral", [6]string{"West Kazakhstan Time", "", "", "", "", ""}},
	{"Asia/Aqtau", [6]string{"West Kazakhstan Time", "", "", "", "", ""}},
	{"Asia/Chita", [6]string{"Yakutsk Standard Time", "", "Yakutsk Summer Time", "", "Yakutsk Time", ""}},
	{"Asia/Dhaka", [6]string{"Bangladesh Standard Time", "", "Bangladesh Summer Time", "", "Bangladesh Time", ""}},
	{"Asia/Dubai", [6]string{"Gulf Standard Time", "", "", "", "", ""}},
	{"Asia/Kabul", [6]string{"Afghanistan Time", "", "", "", "", ""}},
	{"Asia/Macau", [6]string{"China Standard Time", "", "China Daylight Time", "", "China Time", ""}},
	{"Asia/Qatar", [6]string{"Arabian Standard Time", "", "Arabian Daylight Time", "", "Arabian Time", ""}},
	{"Asia/Seoul", [6]string{"Korean Standard Time", "", "Korean Daylight Time", "", "Korean Time", ""}},
	{"Africa/Juba", [6]string{"Central Africa Time", "", "", "", "", ""}},
	{"Africa/Lome", [6]string{"Greenwich Mean Time", "GMT", "", "", "", ""}},
	{"Asia/Almaty", [6]string{"East Kazakhstan Time", "", "", "", "", ""}},
	{"Asia/Anadyr", [6]string{"Anadyr Standard Time", "", "Anadyr Summer Time", "", "Anadyr Time", ""}},
	{"Asia/Aqtobe", [6]string{"West Kazakhstan Time", "", "", "", "", ""}},
	{"Asia/Atyrau", [6]string{"West Kazakhstan Time", "", "", "", "", ""}},
	{"Asia/Beirut", [6]string{"Eastern European Standard Time", "", "Eastern European Summer Time", "", "Eastern European Time", ""}},
	{"Asia/Brunei", [6]string{"Brunei Darussalam Time", "", "", "", "", ""}},
	{"Asia/Harbin", [6]string{"China Standard Time", "", "China Daylight Time", "", "China Time", ""}},
	{"Asia/Hebron", [6]string{"Eastern European Standard Time", "", "Eastern European Summer Time", "", "Eastern European Time", ""}},
	{"Asia/Kuwait", [6]string{"Arabian Standard Time", "", "Arabian Daylight Time", "", "Arabian Time", ""}},
	{"Asia/Manila", [6]string{"Philippine Standard Time", "", "Philippine Summer Time", "", "Philippine Time", ""}},
	{"Asia/Muscat", [6]string{"Gulf Standard Time", "", "", "", "", ""}},
	{"Asia/Riyadh", [6]string{"Arabian Standard Time", "", "Arabian Daylight Time", "", "Arabian Time", ""}},
	{"Asia/Saigon", [6]string{"Indochina Time", "", "", "", "", ""}},
	{"Asia/Taipei", [6]string{"Taipei Standard Time", "", "Taipei Daylight Time", "", "Taipei Time", ""}},
	{"Asia/Tehran", [6]string{"Iran Standard Time", "", "Iran Daylight Time", "", "Iran Time", ""}},
	{"Europe/Kiev", [6]string{"Eastern European Standard Time", "", "Eastern European Summer Time", "", "Eastern European Time", ""}},
	{"Europe/Oslo", [6]string{"Central European Standard Time", "", "Central European Summer Time", "", "Central European Time", ""}},
	{"Europe/Riga", [6]string{"Eastern European Standard Time", "", "Eastern European Summer Time", "", "Eastern European Time", ""}},
	{"Europe/Rome", [6]string{"Central European Standard Time", "", "Central European Summer Time", "", "Central European Time", ""}},
	{"Indian/Mahe", [6]string{"Seychelles Time", "", "", "", "", ""}},
	{"Pacific/Yap", [6]string{"Chuuk Time", "", "", "", "", ""}},
	{"Africa/Accra", [6]string{"Greenwich Mean Time", "GMT", "", "", "", ""}},
	{"Africa/Cairo", [6]string{"Eastern European Standard Time", "", "Eastern European Summer Time", "", "Eastern European Time", ""}},
	{"Africa/Ceuta", [6]string{"Central European Standard Time", "", "Central European Summer Time", "", "Central European Time", ""}},
	{"Africa/Dakar", [6]string{"Greenwich Mean Time", "GMT", "", "", "", ""}},
	{"Africa/Lagos", [6]string{"West Africa Standard Time", "", "West Africa Summer Time", "", "West Africa Time", ""}},
	{"Africa/Tunis", [6]string{"Central European Standard Time", "", "Central European Summer Time", "", "Central European Time", ""}},
	{"America/Adak", [6]string{"Hawaii-Aleutian Standard Time", "HAST", "Hawaii-Aleutian Daylight Time", "HADT", "Hawaii-Aleutian Time", "HAT"}},
	{"America/Lima", [6]string{"Peru Standard Time", "", "Peru Summer Time", "", "Peru Time", ""}},
	{"America/Nome", [6]string{"Alaska Standard Time", "AKST", "Alaska Daylight Time", "AKDT", "Alaska Time", "AKT"}},
	{"Asia/Baghdad", [6]string{"Arabian Standard Time", "", "Arabian Daylight Time", "", "Arabian Time", ""}},
	{"Asia/Bahrain", [6]string{"Arabian Standard Time", "", "Arabian Daylight Time", "", "Arabian Time", ""}},
	{"Asia/Bangkok", [6]string{"Indochina Time", "", "", "", "", ""}},
	{"Asia/Bishkek", [6]string{"Kyrgyzstan Time", "", "", "", "", ""}},
	{"Asia/Colombo", [6]string{"India Standard Time", "", "", "", "", ""}},
	{"Asia/Irkutsk", [6]string{"Irkutsk Standard Time", "", "Irkutsk Summer Time", "", "Irkutsk Time", ""}},
	{"Asia/Jakarta", [6]string{"Western Indonesia Time", "", "", "", "", ""}},
	{"Asia/Karachi", [6]string{"Pakistan Standard Time", "", "Pakistan Summer Time", "", "Pakistan Time", ""}},
	{"Asia/Kuching", [6]string{"Malaysia Time", "", "", "", "", ""}},
	{"Asia/Magadan", [6]string{"Magadan Standard Time", "", "Magadan Summer Time", "", "Magadan Time", ""}},
	{"Asia/Nicosia", [6]string{"Eastern European Standard Time", "", "Eastern European Summer Time", "", "Eastern European Time", ""}},
	{"Asia/Rangoon", [6]string{"Myanmar Time", "", "", "", "", ""}},
	{"Asia/Tbilisi", [6]string{"Georgia Standard Time", "", "Georgia Summer Time", "", "Georgia Time", ""}},
	{"Asia/Thimphu", [6]string{"Bhutan Time", "", "", "", "", ""}},
	{"Asia/Yakutsk", [6]string{"Yakutsk Standard Time", "", "Yakutsk Summer Time", "", "Yakutsk Time", ""}},
	{"Asia/Yerevan", [6]string{"Armenia Standard Time", "", "Armenia Summer Time", "", "Armenia Time", ""}},
	{"Europe/Malta", [6]string{"Central European Standard Time", "", "Central European Summer Time", "", "Central European Time", ""}},
	{"Europe/Minsk", [6]string{"Moscow Standard Time", "", "Moscow Summer Time", "", "Moscow Time", ""}},
	{"Europe/Sofia", [6]string{"Eastern European Standard Time", "", "Eastern European Summer Time", "", "Eastern European Time", ""}},
	{"Europe/Vaduz", [6]string{"Central European Standard Time", "", "Central European Summer Time", "", "Central European Time", ""}},
	{"Indian/Cocos", [6]string{"Cocos Islands Time", "", "", "", "", ""}},
	{"Pacific/Apia", [6]string{"Apia Standard Time", "", "Apia Daylight Time", "", "Apia Time", ""}},
	{"Pacific/Fiji", [6]string{"Fiji Standard Time", "", "Fiji Summer Time", "", "Fiji Time", ""}},
	{"Pacific/Guam", [6]string{"Chamorro Standard Time", "", "", "", "", ""}},
	{"Pacific/Niue", [6]string{"Niue Time", "", "", "", "", ""}},
	{"Pacific/Truk", [6]string{"Chuuk Time", "", "", "", "", ""}},
	{"Pacific/Wake", [6]string{"Wake Island Time", "", "", "", "", ""}},
	{"SystemV/AST4", [6]string{"Atlantic Standard Time", "AST", "Atlantic Daylight Time", "ADT", "Atlantic Time", "AT"}},
	{"SystemV/CST6", [6]string{"Central Standard Time", "CST", "Central Daylight Time", "CDT", "Central Time", "CT"}},
	{"SystemV/EST5", [6]string{"Eastern Standard Time", "EST", "Eastern Daylight Time", "EDT", "Eastern Time", "ET"}},
	{"SystemV/MST7", [6]string{"Mountain Standard Time", "MST", "Mountain Daylight Time", "MDT", "Mountain Time", "MT"}},
	{"SystemV/PST8", [6]string{"Pitcairn Time", "", "", "", "", ""}},
	{"SystemV/YST9", [6]string{"Gambier Time", "", "", "", "", ""}},
	{"Africa/Asmera", [6]string{"East Africa Time", "", "", "", "", ""}},
	{"Africa/Bamako", [6]string{"Greenwich Mean Time", "GMT", "", "", "", ""}},
	{"Africa/Bangui", [6]string{"West Africa Standard Time", "", "West Africa Summer Time", "", "West Africa Time", ""}},
	{"Africa/Banjul", [6]string{"Greenwich Mean Time", "GMT", "", "", "", ""}},
	{"Africa/Bissau", [6]string{"Greenwich Mean Time", "GMT", "", "", "", ""}},
	{"Africa/Douala", [6]string{"West Africa Standard Time", "", "West Africa Summer Time", "", "West Africa Time", ""}},
	{"Africa/Harare", [6]string{"Central Africa Time", "", "", "", "", ""}},
	{"Africa/Kigali", [6]string{"Central Africa Time", "", "", "", "", ""}},
	{"Africa/Luanda", [6]string{"West Africa Standard Time", "", "West Africa Summer Time", "", "West Africa Time", ""}},
	{"Africa/Lusaka", [6]string{"Central Africa Time", "", "", "", "", ""}},
	{"Africa/Malabo", [6]string{"West Africa Standard Time", "", "West Africa Summer Time", "", "West Africa Time", ""}},
	{"Africa/Maputo", [6]string{"Central Africa Time", "", "", "", "", ""}},
	{"Africa/Maseru", [6]string{"South Africa Standard Time", "", "", "", "", ""}},
	{"Africa/Niamey", [6]string{"West Africa Standard Time", "", "West Africa Summer Time", "", "West Africa Time", ""}},
	{"America/Aruba", [6]string{"Atlantic Standard Time", "AST", "Atlantic Daylight Time", "ADT", "Atlantic Time", "AT"}},
	{"America/Bahia", [6]string{"Brasilia Standard Time", "", "Brasilia Summer Time", "", "Brasilia Time", ""}},
	{"America/Belem", [6]string{"Brasilia Standard Time", "", "Brasilia Summer Time", "", "Brasilia Time", ""}},
	{"America/Boise", [6]string{"Mountain Standard Time", "MST", "Mountain Daylight Time", "MDT", "Mountain Time", "MT"}},
	{"America/Jujuy", [6]string{"Argentina Standard Time", "", "Argentina Summer Time", "", "Argentina Time", ""}},
	{"America/Thule", [6]string{"Atlantic Standard Time", "AST", "Atlantic Daylight Time", "ADT", "Atlantic Time", "AT"}},
	{"Asia/Ashgabat", [6]string{"Turkmenistan Standard Time", "", "Turkmenistan Summer Time", "", "Turkmenistan Time", ""}},
	{"Asia/Calcutta", [6]string{"India Standard Time", "", "", "", "", ""}},
	{"Asia/Dushanbe", [6]string{"Tajikistan Time", "", "", "", "", ""}},
	{"Asia/Jayapura", [6]string{"Eastern Indonesia Time", "", "", "", "", ""}},
	{"Asia/Katmandu", [6]string{"Nepal Time", "", "", "", "", ""}},
	{"Asia/Khandyga", [6]string{"Yakutsk Standard Time", "", "Yakutsk Summer Time", "", "Yakutsk Time", ""}},
	{"Asia/Makassar", [6]string{"Central Indonesia Time", "", "", "", "", ""}},
	{"Asia/Qostanay", [6]string{"East Kazakhstan Time", "", "", "", "", ""}},
	{"Asia/Sakhalin", [6]string{"Sakhalin Standard Time", "", "Sakhalin Summer Time", "", "Sakhalin Time", ""}},
	{"Asia/Tashkent", [6]string{"Uzbekistan Standard Time", "", "Uzbekistan Summer Time", "", "Uzbekistan Time", ""}},
	{"Asia/Ust-Nera", [6]string{"Vladivostok Standard Time", "", "Vladivostok Summer Time", "", "Vladivostok Time", ""}},
	{"Europe/Athens", [6]string{"Eastern European Standard Time", "", "Eastern European Summer Time", "", "Eastern European Time", ""}},
	{"Europe/Berlin", [6]string{"Central European Standard Time", "", "Central European Summer Time", "", "Central European Time", ""}},
	{"Europe/Dublin", [6]string{"Greenwich Mean Time", "GMT", "Irish Standard Time", "", "", ""}},
	{"Europe/Jersey", [6]string{"Greenwich Mean Time", "GMT", "", "", "", ""}},
	{"Europe/Lisbon", [6]string{"Western European Standard Time", "", "Western European Summer Time", "", "Western European Time", ""}},
	{"Europe/London", [6]string{"Greenwich Mean Time", "GMT", "British Summer Time", "", "", ""}},
	{"Europe/Madrid", [6]string{"Central European Standard Time", "", "Central European Summer Time", "", "Central European Time", ""}},
	{"Europe/Monaco", [6]string{"Central European Standard Time", "", "Central European Summer Time", "", "Central European Time", ""}},
	{"Europe/Moscow", [6]string{"Moscow Standard Time", "", "Moscow Summer Time", "", "Moscow Time", ""}},
	{"Europe/Prague", [6]string{"Central European Standard Time", "", "Central European Summer Time", "", "Central European Time", ""}},
	{"Europe/Samara", [6]string{"Samara Standard Time", "", "Samara Summer Time", "", "Samara Time", ""}},
	{"Europe/Skopje", [6]string{"Central European Standard Time", "", "Central European Summer Time", "", "Central European Time", ""}},
	{"Europe/Tirane", [6]string{"Central European Standard Time", "", "Central European Summer Time", "", "Central European Time", ""}},
	{"Europe/Vienna", [6]string{"Central European Standard Time", "", "Central European Summer Time", "", "Central European Time", ""}},
	{"Europe/Warsaw", [6]string{"Central European Standard Time", "", "Central European Summer Time", "", "Central European Time", ""}},
	{"Europe/Zagreb", [6]string{"Central European Standard Time", "", "Central European Summer Time", "", "Central European Time", ""}},
	{"Europe/Zurich", [6]string{"Central European Standard Time", "", "Central European Summer Time", "", "Central European Time", ""}},
	{"Indian/Chagos", [6]string{"Indian Ocean Time", "", "", "", "", ""}},
	{"Indian/Comoro", [6]string{"East Africa Time", "", "", "", "", ""}},
	{"Pacific/Efate", [6]string{"Vanuatu Standard Time", "", "Vanuatu Summer Time", "", "Vanuatu Time", ""}},
	{"Pacific/Nauru", [6]string{"Nauru Time", "", "", "", "", ""}},
	{"Pacific/Palau", [6]string{"Palau Time", "", "", "", "", ""}},
	{"SystemV/HST10", [6]string{"Hawaii-Aleutian Standard Time", "HST", "Hawaii-Aleutian Daylight Time", "HDT", "Hawaii-Aleutian Time", "HST"}},
	{"Africa/Abidjan", [6]string{"Greenwich Mean Time", "GMT", "", "", "", ""}},
	{"Africa/Algiers", [6]string{"Central European Standard Time", "", "Central European Summer Time", "", "Central European Time", ""}},
	{"Africa/Conakry", [6]string{"Greenwich Mean Time", "GMT", "", "", "", ""}},
	{"Africa/Kampala", [6]string{"East Africa Time", "", "", "", "", ""}},
	{"Africa/Mbabane", [6]string{"South Africa Standard Time", "", "", "", "", ""}},
	{"Africa/Nairobi", [6]string{"East Africa Time", "", "", "", "", ""}},
	{"Africa/Tripoli", [6]string{"Eastern European Standard Time", "", "Eastern European Summer Time", "", "Eastern European Time", ""}},
	{"America/Belize", [6]string{"Central Standard Time", "CST", "Central Daylight Time", "CDT", "Central Time", "CT"}},
	{"America/Bogota", [6]string{"Colombia Standard Time", "", "Colombia Summer Time", "", "Colombia Time", ""}},
	{"America/Cancun", [6]string{"Eastern Standard Time", "EST", "Eastern Daylight Time", "EDT", "Eastern Time", "ET"}},
	{"America/Cayman", [6]string{"Eastern Standard Time", "EST", "Eastern Daylight Time", "EDT", "Eastern Time", "ET"}},
	{"America/Cuiaba", [6]string{"Amazon Standard Time", "", "Amazon Summer Time", "", "Amazon Time", ""}},
	{"America/Dawson", [6]string{"Yukon Time", "", "", "", "", ""}},
	{"America/Guyana", [6]string{"Guyana Time", "", "", "", "", ""}},
	{"America/Havana", [6]string{"Cuba Standard Time", "", "Cuba Daylight Time", "", "Cuba Time", ""}},
	{"America/Inuvik", [6]string{"Mountain Standard Time", "MST", "Mountain Daylight Time", "MDT", "Mountain Time", "MT"}},
	{"America/Juneau", [6]string{"Alaska Standard Time", "AKST", "Alaska Daylight Time", "AKDT", "Alaska Time", "AKT"}},
	{"America/La_Paz", [6]string{"Bolivia Time", "", "", "", "", ""}},
	{"America/Maceio", [6]string{"Brasilia Standard Time", "", "Brasilia Summer Time", "", "Brasilia Time", ""}},
	{"America/Manaus", [6]string{"Amazon Standard Time", "", "Amazon Summer Time", "", "Amazon Time", ""}},
	{"America/Merida", [6]string{"Central Standard Time", "CST", "Central Daylight Time", "CDT", "Central Time", "CT"}},
	{"America/Nassau", [6]string{"Eastern Standard Time", "EST", "Eastern Daylight Time", "EDT", "Eastern Time", "ET"}},
	{"America/Panama", [6]string{"Eastern Standard Time", "EST", "Eastern Daylight Time", "EDT", "Eastern Time", "ET"}},
	{"America/Recife", [6]string{"Brasilia Standard Time", "", "Brasilia Summer Time", "", "Brasilia Time", ""}},
	{"America/Regina", [6]string{"Central Standard Time", "CST", "Central Daylight Time", "CDT", "Central Time", "CT"}},
	{"Asia/Chongqing", [6]string{"China Standard Time", "", "China Daylight Time", "", "China Time", ""}},
	{"Asia/Hong_Kong", [6]string{"Hong Kong Standard Time", "", "Hong Kong Summer Time", "", "Hong Kong Time", ""}},
	{"Asia/Kamchatka", [6]string{"Petropavlovsk-Kamchatski Standard Time", "", "Petropavlovsk-Kamchatski Summer Time", "", "Petropavlovsk-Kamchatski Time", ""}},
	{"Asia/Pontianak", [6]string{"Western Indonesia Time", "", "", "", "", ""}},
	{"Asia/Pyongyang", [6]string{"Korean Standard Time", "", "Korean Daylight Time", "", "Korean Time", ""}},
	{"Asia/Qyzylorda", [6]string{"West Kazakhstan Time", "", "", "", "", ""}},
	{"Asia/Samarkand", [6]string{"Uzbekistan Standard Time", "", "Uzbekistan Summer Time", "", "Uzbekistan Time", ""}},
	{"Asia/Singapore", [6]string{"Singapore Standard Time", "", "", "", "", ""}},
	{"Asia/Vientiane", [6]string{"Indochina Time", "", "", "", "", ""}},
	{"Europe/Andorra", [6]string{"Central European Standard Time", "", "Central European Summer Time", "", "Central European Time", ""}},
	{"Europe/Belfast", [6]string{"Greenwich Mean Time", "GMT", "British Summer Time", "", "", ""}},
	{"Europe/Tallinn", [6]string{"Eastern European Standard Time", "", "Eastern European Summer Time", "", "Eastern European Time", ""}},
	{"Europe/Vatican", [6]string{"Central European Standard Time", "", "Central European Summer Time", "", "Central European Time", ""}},
	{"Europe/Vilnius", [6]string{"Eastern European Standard Time", "", "Eastern European Summer Time", "", "Eastern European Time", ""}},
	{"Indian/Mayotte", [6]string{"East Africa Time", "", "", "", "", ""}},
	{"Indian/Reunion", [6]string{"Réunion Time", "", "", "", "", ""}},
	{"Pacific/Easter", [6]string{"Easter Island Standard Time", "", "Easter Island Summer Time", "", "Easter Island Time", ""}},
	{"Pacific/Kosrae", [6]string{"Kosrae Time", "", "", "", "", ""}},
	{"Pacific/Majuro", [6]string{"Marshall Islands Time", "", "", "", "", ""}},
	{"Pacific/Midway", [6]string{"Samoa Standard Time", "", "Samoa Daylight Time", "", "Samoa Time", ""}},
	{"Pacific/Noumea", [6]string{"New Caledonia Standard Time", "", "New Caledonia Summer Time", "", "New Caledonia Time", ""}},
	{"Pacific/Ponape", [6]string{"Ponape Time", "", "", "", "", ""}},
	{"Pacific/Saipan", [6]string{"Chamorro Standard Time", "", "", "", "", ""}},
	{"Pacific/Tahiti", [6]string{"Tahiti Time", "", "", "", "", ""}},
	{"Pacific/Tarawa", [6]string{"Gilbert Islands Time", "", "", "", "", ""}},
	{"Pacific/Wallis", [6]string{"Wallis & Futuna Time", "", "", "", "", ""}},
	{"Africa/Blantyre", [6]string{"Central Africa Time", "", "", "", "", ""}},
	{"Africa/Djibouti", [6]string{"East Africa Time", "", "", "", "", ""}},
	{"Africa/Freetown", [6]string{"Greenwich Mean Time", "GMT", "", "", "", ""}},
	{"Africa/Gaborone", [6]string{"Central Africa Time", "", "", "", "", ""}},
	{"Africa/Khartoum", [6]string{"Central Africa Time", "", "", "", "", ""}},
	{"Africa/Kinshasa", [6]string{"West Africa Standard Time", "", "West Africa Summer Time", "", "West Africa Time", ""}},
	{"Africa/Monrovia", [6]string{"Greenwich Mean Time", "GMT", "", "", "", ""}},
	{"Africa/Ndjamena", [6]string{"West Africa Standard Time", "", "West Africa Summer Time", "", "West Africa Time", ""}},
	{"Africa/Sao_Tome", [6]string{"Greenwich Mean Time", "GMT", "", "", "", ""}},
	{"Africa/Timbuktu", [6]string{"Greenwich Mean Time", "GMT", "", "", "", ""}},
	{"Africa/Windhoek", [6]string{"Central Africa Time", "", "", "", "", ""}},
	{"America/Antigua", [6]string{"Atlantic Standard Time", "AST", "Atlantic Daylight Time", "ADT", "Atlantic Time", "AT"}},
	{"America/Caracas", [6]string{"Venezuela Time", "", "", "", "", ""}},
	{"America/Cayenne", [6]string{"French Guiana Time", "", "", "", "", ""}},
	{"America/Cordoba", [6]string{"Argentina Standard Time", "", "Argentina Summer Time", "", "Argentina Time", ""}},
	{"America/Creston", [6]string{"Mountain Standard Time", "MST", "Mountain Daylight Time", "MDT", "Mountain Time", "MT"}},
	{"America/Curacao", [6]string{"Atlantic Standard Time", "AST", "Atlantic Daylight Time", "ADT", "Atlantic Time", "AT"}},
	{"America/Detroit", [6]string{"Eastern Standard Time", "EST", "Eastern Daylight Time", "EDT", "Eastern Time", "ET"}},
	{"America/Godthab", [6]string{"West Greenland Standard Time", "", "West Greenland Summer Time", "", "West Greenland Time", ""}},
	{"America/Grenada", [6]string{"Atlantic Standard Time", "AST", "Atlantic Daylight Time", "ADT", "Atlantic Time", "AT"}},
	{"America/Iqaluit", [6]string{"Eastern Standard Time", "EST", "Eastern Daylight Time", "EDT", "Eastern Time", "ET"}},
	{"America/Jamaica", [6]string{"Eastern Standard Time", "EST", "Eastern Daylight Time", "EDT", "Eastern Time", "ET"}},
	{"America/Managua", [6]string{"Central Standard Time", "CST", "Central Daylight Time", "CDT", "Central Time", "CT"}},
	{"America/Marigot", [6]string{"Atlantic Standard Time", "AST", "Atlantic Daylight Time", "ADT", "Atlantic Time", "AT"}},
	{"America/Mendoza", [6]string{"Argentina Standard Time", "", "Argentina Summer Time", "", "Argentina Time", ""}},
	{"America/Moncton", [6]string{"Atlantic Standard Time", "AST", "Atlantic Daylight Time", "ADT", "Atlantic Time", "AT"}},
	{"America/Nipigon", [6]string{"Eastern Standard Time", "EST", "Eastern Daylight Time", "EDT", "Eastern Time", "ET"}},
	{"America/Noronha", [6]string{"Fernando de Noronha Standard Time", "", "Fernando de Noronha Summer Time", "", "Fernando de Noronha Time", ""}},
	{"America/Ojinaga", [6]string{"Central Standard Time", "CST", "Central Daylight Time", "CDT", "Central Time", "CT"}},
	{"America/Tijuana", [6]string{"Pacific Standard Time", "PST", "Pacific Daylight Time", "PDT", "Pacific Time", "PT"}},
	{"America/Toronto", [6]string{"Eastern Standard Time", "EST", "Eastern Daylight Time", "EDT", "Eastern Time", "ET"}},
	{"America/Tortola", [6]string{"Atlantic Standard Time", "AST", "Atlantic Daylight Time", "ADT", "Atlantic Time", "AT"}},
	{"America/Yakutat", [6]string{"Alaska Standard Time", "AKST", "Alaska Daylight Time", "AKDT", "Alaska Time", "AKT"}},
	{"Asia/Choibalsan", [6]string{"Ulaanbaatar Standard Time", "", "Ulaanbaatar Summer Time", "", "Ulaanbaatar Time", ""}},
	{"Asia/Phnom_Penh", [6]string{"Indochina Time", "", "", "", "", ""}},
	{"Atlantic/Azores", [6]string{"Azores Standard Time", "", "Azores Summer Time", "", "Azores Time", ""}},
	{"Atlantic/Canary", [6]string{"Western European Standard Time", "", "Western European Summer Time", "", "Western European Time", ""}},
	{"Atlantic/Faeroe", [6]string{"Western European Standard Time", "", "Western European Summer Time", "", "Western European Time", ""}},
	{"Australia/Eucla", [6]string{"Australian Central Western Standard Time", "", "Australian Central Western Daylight Time", "", "Australian Central Western Time", ""}},
	{"Australia/Perth", [6]string{"Australian Western Standard Time", "", "Australian Western Daylight Time", "", "Western Australia Time", ""}},
	{"Europe/Belgrade", [6]string{"Central European Standard Time", "", "Central European Summer Time", "", "Central European Time", ""}},
	{"Europe/Brussels", [6]string{"Central European Standard Time", "", "Central European Summer Time", "", "Central European Time", ""}},
	{"Europe/Budapest", [6]string{"Central European Standard Time", "", "Central European Summer Time", "", "Central European Time", ""}},
	{"Europe/Busingen", [6]string{"Central European Standard Time", "", "Central European Summer Time", "", "Central European Time", ""}},
	{"Europe/Chisinau", [6]string{"Eastern European Standard Time", "", "Eastern European Summer Time", "", "Eastern European Time", ""}},
	{"Europe/Guernsey", [6]string{"Greenwich Mean Time", "GMT", "", "", "", ""}},
	{"Europe/Helsinki", [6]string{"Eastern European Standard Time", "", "Eastern European Summer Time", "", "Eastern European Time", ""}},
	{"Europe/Sarajevo", [6]string{"Central European Standard Time", "", "Central European Summer Time", "", "Central European Time", ""}},
	{"Europe/Uzhgorod", [6]string{"Eastern European Standard Time", "", "Eastern European Summer Time", "", "Eastern European Time", ""}},
	{"Indian/Maldives", [6]string{"Maldives Time", "", "", "", "", ""}},
	{"Pacific/Chatham", [6]string{"Chatham Standard Time", "", "Chatham Daylight Time", "", "Chatham Time", ""}},
	{"Pacific/Fakaofo", [6]string{"Tokelau Time", "", "", "", "", ""}},
	{"Pacific/Gambier", [6]string{"Gambier Time", "", "", "", "", ""}},
	{"Pacific/Norfolk", [6]string{"Norfolk Island Standard Time", "", "Norfolk Island Daylight Time", "", "Norfolk Island Time", ""}},
	{"SystemV/AST4ADT", [6]string{"Atlantic Standard Time", "AST", "Atlantic Daylight Time", "ADT", "Atlantic Time", "AT"}},
	{"SystemV/CST6CDT", [6]string{"Central Standard Time", "CST", "Central Daylight Time", "CDT", "Central Time", "CT"}},
	{"SystemV/EST5EDT", [6]string{"Eastern Standard Time", "EST", "Eastern Daylight Time", "EDT", "Eastern Time", "ET"}},
	{"SystemV/MST7MDT", [6]string{"Mountain Standard Time", "MST", "Mountain Daylight Time", "MDT", "Mountain Time", "MT"}},
	{"SystemV/PST8PDT", [6]string{"Pacific Standard Time", "PST", "Pacific Daylight Time", "PDT", "Pacific Time", "PT"}},
	{"SystemV/YST9YDT", [6]string{"Alaska Standard Time", "AKST", "Alaska Daylight Time", "AKDT", "Alaska Time", "AKT"}},
	{"Africa/Bujumbura", [6]string{"Central Africa Time", "", "", "", "", ""}},
	{"Africa/Mogadishu", [6]string{"East Africa Time", "", "", "", "", ""}},
	{"America/Anguilla", [6]string{"Atlantic Standard Time", "AST", "Atlantic Daylight Time", "ADT", "Atlantic Time", "AT"}},
	{"America/Asuncion", [6]string{"Paraguay Standard Time", "", "Paraguay Summer Time", "", "Paraguay Time", ""}},
	{"America/Barbados", [6]string{"Atlantic Standard Time", "AST", "Atlantic Daylight Time", "ADT", "Atlantic Time", "AT"}},
	{"America/Dominica", [6]string{"Atlantic Standard Time", "AST", "Atlantic Daylight Time", "ADT", "Atlantic Time", "AT"}},
	{"America/Edmonton", [6]string{"Mountain Standard Time", "MST", "Mountain Daylight Time", "MDT", "Mountain Time", "MT"}},
	{"America/Eirunepe", [6]string{"Acre Standard Time", "", "Acre Summer Time", "", "Acre Time", ""}},
	{"America/Mazatlan", [6]string{"Mexican Pacific Standard Time", "", "Mexican Pacific Daylight Time", "", "Mexican Pacific Time", ""}},
	{"America/Miquelon", [6]string{"St. Pierre & Miquelon Standard Time", "", "St. Pierre & Miquelon Daylight Time", "", "St. Pierre & Miquelon Time", ""}},
	{"America/Montreal", [6]string{"Eastern Standard Time", "EST", "Eastern Daylight Time", "EDT", "Eastern Time", "ET"}},
	{"America/Resolute", [6]string{"Central Standard Time", "CST", "Central Daylight Time", "CDT", "Central Time", "CT"}},
	{"America/Santarem", [6]string{"Brasilia Standard Time", "", "Brasilia Summer Time", "", "Brasilia Time", ""}},
	{"America/Santiago", [6]string{"Chile Standard Time", "", "Chile Summer Time", "", "Chile Time", ""}},
	{"America/Shiprock", [6]string{"Mountain Standard Time", "MST", "Mountain Daylight Time", "MDT", "Mountain Time", "MT"}},
	{"America/St_Kitts", [6]string{"Atlantic Standard Time", "AST", "Atlantic Daylight Time", "ADT", "Atlantic Time", "AT"}},
	{"America/St_Lucia", [6]string{"Atlantic Standard Time", "AST", "Atlantic Daylight Time", "ADT", "Atlantic Time", "AT"}},
	{"America/Winnipeg", [6]string{"Central Standard Time", "CST", "Central Daylight Time", "CDT", "Central Time", "CT"}},
	{"Antarctica/Casey", [6]string{"Casey Time", "", "", "", "", ""}},
	{"Antarctica/Davis", [6]string{"Davis Time", "", "", "", "", ""}},
	{"Antarctica/Syowa", [6]string{"Syowa Time", "", "", "", "", ""}},
	{"Antarctica/Troll", [6]string{"Greenwich Mean Time", "GMT", "", "", "", ""}},
	{"Asia/Krasnoyarsk", [6]string{"Krasnoyarsk Standard Time", "", "Krasnoyarsk Summer Time", "", "Krasnoyarsk Time", ""}},
	{"Asia/Novosibirsk", [6]string{"Novosibirsk Standard Time", "", "Novosibirsk Summer Time", "", "Novosibirsk Time", ""}},
	{"Asia/Ulaanbaatar", [6]string{"Ulaanbaatar Standard Time", "", "Ulaanbaatar Summer Time", "", "Ulaanbaatar Time", ""}},
	{"Asia/Vladivostok", [6]string{"Vladivostok Standard Time", "", "Vladivostok Summer Time", "", "Vladivostok Time", ""}},
	{"Atlantic/Bermuda", [6]string{"Atlantic Standard Time", "AST", "Atlantic Daylight Time", "ADT", "Atlantic Time", "AT"}},
	{"Atlantic/Madeira", [6]string{"Western European Standard Time", "", "Western European Summer Time", "", "Western European Time", ""}},
	{"Atlantic/Stanley", [6]string{"Falkland Islands Standard Time", "", "Falkland Islands Summer Time", "", "Falkland Islands Time", ""}},
	{"Australia/Currie", [6]string{"Australian Eastern Standard Time", "", "Australian Eastern Daylight Time", "", "Eastern Australia Time", ""}},
	{"Australia/Darwin", [6]string{"Australian Central Standard Time", "", "Australian Central Daylight Time", "", "Central Australia Time", ""}},
	{"Australia/Hobart", [6]string{"Australian Eastern Standard Time", "", "Australian Eastern Daylight Time", "", "Eastern Australia Time", ""}},
	{"Australia/Sydney", [6]string{"Australian Eastern Standard Time", "", "Australian Eastern Daylight Time", "", "Eastern Australia Time", ""}},
	{"Europe/Amsterdam", [6]string{"Central European Standard Time", "", "Central European Summer Time", "", "Central European Time", ""}},
	{"Europe/Gibraltar", [6]string{"Central European Standard Time", "", "Central European Summer Time", "", "Central European Time", ""}},
	{"Europe/Ljubljana", [6]string{"Central European Standard Time", "", "Central European Summer Time", "", "Central European Time", ""}},
	{"Europe/Mariehamn", [6]string{"Eastern European Standard Time", "", "Eastern European Summer Time", "", "Eastern European Time", ""}},
	{"Europe/Podgorica", [6]string{"Central European Standard Time", "", "Central European Summer Time", "", "Central European Time", ""}},
	{"Europe/Stockholm", [6]string{"Central European Standard Time", "", "Central European Summer Time", "", "Central European Time", ""}},
	{"Europe/Volgograd", [6]string{"Volgograd Standard Time", "", "Volgograd Summer Time", "", "Volgograd Time", ""}},
	{"Indian/Christmas", [6]string{"Christmas Island Time", "", "", "", "", ""}},
	{"Indian/Kerguelen", [6]string{"French Southern & Antarctic Time", "", "", "", "", ""}},
	{"Indian/Mauritius", [6]string{"Mauritius Standard Time", "", "Mauritius Summer Time", "", "Mauritius Time", ""}},
	{"Pacific/Auckland", [6]string{"New Zealand Standard Time", "", "New Zealand Daylight Time", "", "New Zealand Time", ""}},
	{"Pacific/Funafuti", [6]string{"Tuvalu Time", "", "", "", "", ""}},
	{"Pacific/Johnston", [6]string{"Hawaii-Aleutian Standard Time", "HAST", "Hawaii-Aleutian Daylight Time", "HADT", "Hawaii-Aleutian Time", "HAT"}},
	{"Pacific/Pitcairn", [6]string{"Pitcairn Time", "", "", "", "", ""}},
	{"Africa/Libreville", [6]string{"West Africa Standard Time", "", "West Africa Summer Time", "", "West Africa Time", ""}},
	{"Africa/Lubumbashi", [6]string{"Central Africa Time", "", "", "", "", ""}},
	{"Africa/Nouakchott", [6]string{"Greenwich Mean Time", "GMT", "", "", "", ""}},
	{"Africa/Porto-Novo", [6]string{"West Africa Standard Time", "", "West Africa Summer Time", "", "West Africa Time", ""}},
	{"America/Araguaina", [6]string{"Brasilia Standard Time", "", "Brasilia Summer Time", "", "Brasilia Time", ""}},
	{"America/Boa_Vista", [6]string{"Amazon Standard Time", "", "Amazon Summer Time", "", "Amazon Time", ""}},
	{"America/Catamarca", [6]string{"Argentina Standard Time", "", "Argentina Summer Time", "", "Argentina Time", ""}},
	{"America/Chihuahua", [6]string{"Central Standard Time", "CST", "Central Daylight Time", "CDT", "Central Time", "CT"}},
	{"America/Fortaleza", [6]string{"Brasilia Standard Time", "", "Brasilia Summer Time", "", "Brasilia Time", ""}},
	{"America/Glace_Bay", [6]string{"Atlantic Standard Time", "AST", "Atlantic Daylight Time", "ADT", "Atlantic Time", "AT"}},
	{"America/Goose_Bay", [6]string{"Atlantic Standard Time", "AST", "Atlantic Daylight Time", "ADT", "Atlantic Time", "AT"}},
	{"America/Guatemala", [6]string{"Central Standard Time", "CST", "Central Daylight Time", "CDT", "Central Time", "CT"}},
	{"America/Guayaquil", [6]string{"Ecuador Time", "", "", "", "", ""}},
	{"America/Matamoros", [6]string{"Central Standard Time", "CST", "Central Daylight Time", "CDT", "Central Time", "CT"}},
	{"America/Menominee", [6]string{"Central Standard Time", "CST", "Central Daylight Time", "CDT", "Central Time", "CT"}},
	{"America/Monterrey", [6]string{"Central Standard Time", "CST", "Central Daylight Time", "CDT", "Central Time", "CT"}},
	{"America/Sao_Paulo", [6]string{"Brasilia Standard Time", "", "Brasilia Summer Time", "", "Brasilia Time", ""}},
	{"America/St_Thomas", [6]string{"Atlantic Standard Time", "AST", "Atlantic Daylight Time", "ADT", "Atlantic Time", "AT"}},
	{"America/Vancouver", [6]string{"Pacific Standard Time", "PST", "Pacific Daylight Time", "PDT", "Pacific Time", "PT"}},
	{"Antarctica/Mawson", [6]string{"Mawson Time", "", "", "", "", ""}},
	{"Antarctica/Vostok", [6]string{"Vostok Time", "", "", "", "", ""}},
	{"Asia/Kuala_Lumpur", [6]string{"Malaysia Time", "", "", "", "", ""}},
	{"Asia/Novokuznetsk", [6]string{"Krasnoyarsk Standard Time", "", "Krasnoyarsk Summer Time", "", "Krasnoyarsk Time", ""}},
	{"Europe/Bratislava", [6]string{"Central European Standard Time", "", "Central European Summer Time", "", "Central European Time", ""}},
	{"Europe/Copenhagen", [6]string{"Central European Standard Time", "", "Central European Summer Time", "", "Central European Time", ""}},
	{"Europe/Luxembourg", [6]string{"Central European Standard Time", "", "Central European Summer Time", "", "Central European Time", ""}},
	{"Europe/San_Marino", [6]string{"Central European Standard Time", "", "Central European Summer Time", "", "Central European Time", ""}},
	{"Europe/Simferopol", [6]string{"Moscow Standard Time", "", "Moscow Summer Time", "", "Moscow Time", ""}},
	{"Europe/Zaporozhye", [6]string{"Eastern European Standard Time", "", "Eastern European Summer Time", "", "Eastern European Time", ""}},
	{"Pacific/Enderbury", [6]string{"Phoenix Islands Time", "", "", "", "", ""}},
	{"Pacific/Galapagos", [6]string{"Galapagos Time", "", "", "", "", ""}},
	{"Pacific/Kwajalein", [6]string{"Marshall Islands Time", "", "", "", "", ""}},
	{"Pacific/Marquesas", [6]string{"Marquesas Time", "", "", "", "", ""}},
	{"Pacific/Pago_Pago", [6]string{"Samoa Standard Time", "", "Samoa Daylight Time", "", "Samoa Time", ""}},
	{"Pacific/Rarotonga", [6]string{"Cook Islands Standard Time", "", "Cook Islands Half Summer Time", "", "Cook Islands Time", ""}},
	{"Pacific/Tongatapu", [6]string{"Tonga Standard Time", "", "Tonga Summer Time", "", "Tonga Time", ""}},
	{"Africa/Addis_Ababa", [6]string{"East Africa Time", "", "", "", "", ""}},
	{"Africa/Brazzaville", [6]string{"West Africa Standard Time", "", "West Africa Summer Time", "", "West Africa Time", ""}},
	{"Africa/Ouagadougou", [6]string{"Greenwich Mean Time", "GMT", "", "", "", ""}},
	{"America/Costa_Rica", [6]string{"Central Standard Time", "CST", "Central Daylight Time", "CDT", "Central Time", "CT"}},
	{"America/Grand_Turk", [6]string{"Eastern Standard Time", "EST", "Eastern Daylight Time", "EDT", "Eastern Time", "ET"}},
	{"America/Guadeloupe", [6]string{"Atlantic Standard Time", "AST", "Atlantic Daylight Time", "ADT", "Atlantic Time", "AT"}},
	{"America/Hermosillo", [6]string{"Mexican Pacific Standard Time", "", "Mexican Pacific Daylight Time", "", "Mexican Pacific Time", ""}},
	{"America/Kralendijk", [6]string{"Atlantic Standard Time", "AST", "Atlantic Daylight Time", "ADT", "Atlantic Time", "AT"}},
	{"America/Louisville", [6]string{"Eastern Standard Time", "EST", "Eastern Daylight Time", "EDT", "Eastern Time", "ET"}},
	{"America/Martinique", [6]string{"Atlantic Standard Time", "AST", "Atlantic Daylight Time", "ADT", "Atlantic Time", "AT"}},
	{"America/Metlakatla", [6]string{"Alaska Standard Time", "AKST", "Alaska Daylight Time", "AKDT", "Alaska Time", "AKT"}},
	{"America/Montevideo", [6]string{"Uruguay Standard Time", "", "Uruguay Summer Time", "", "Uruguay Time", ""}},
	{"America/Montserrat", [6]string{"Atlantic Standard Time", "AST", "Atlantic Daylight Time", "ADT", "Atlantic Time", "AT"}},
	{"America/Paramaribo", [6]string{"Suriname Time", "", "", "", "", ""}},
	{"America/Rio_Branco", [6]string{"Acre Standard Time", "", "Acre Summer Time", "", "Acre Time", ""}},
	{"America/St_Vincent", [6]string{"Atlantic Standard Time", "AST", "Atlantic Daylight Time", "ADT", "Atlantic Time", "AT"}},
	{"America/Whitehorse", [6]string{"Yukon Time", "", "", "", "", ""}},
	{"Antarctica/McMurdo", [6]string{"New Zealand Standard Time", "", "New Zealand Daylight Time", "", "New Zealand Time", ""}},
	{"Antarctica/Rothera", [6]string{"Rothera Time", "", "", "", "", ""}},
	{"Asia/Yekaterinburg", [6]string{"Yekaterinburg Standard Time", "", "Yekaterinburg Summer Time", "", "Yekaterinburg Time", ""}},
	{"Atlantic/Jan_Mayen", [6]string{"Central European Standard Time", "", "Central European Summer Time", "", "Central European Time", ""}},
	{"Atlantic/Reykjavik", [6]string{"Greenwich Mean Time", "GMT", "", "", "", ""}},
	{"Atlantic/St_Helena", [6]string{"Greenwich Mean Time", "GMT", "", "", "", ""}},
	{"Australia/Adelaide", [6]string{"Australian Central Standard Time", "", "Australian Central Daylight Time", "", "Central Australia Time", ""}},
	{"Australia/Brisbane", [6]string{"Australian Eastern Standard Time", "", "Australian Eastern Daylight Time", "", "Eastern Australia Time", ""}},
	{"Australia/Lindeman", [6]string{"Australian Eastern Standard Time", "", "Australian Eastern Daylight Time", "", "Eastern Australia Time", ""}},
	{"Europe/Isle_of_Man", [6]string{"Greenwich Mean Time", "GMT", "", "", "", ""}},
	{"Europe/Kaliningrad", [6]string{"Eastern European Standard Time", "", "Eastern European Summer Time", "", "Eastern European Time", ""}},
	{"Pacific/Kiritimati", [6]string{"Line Islands Time", "", "", "", "", ""}},
	{"Africa/Johannesburg", [6]string{"South Africa Standard Time", "", "", "", "", ""}},
	{"America/El_Salvador", [6]string{"Central Standard Time", "CST", "Central Daylight Time", "CDT", "Central Time", "CT"}},
	{"America/Fort_Nelson", [6]string{"Mountain Standard Time", "MST", "Mountain Daylight Time", "MDT", "Mountain Time", "MT"}},
	{"America/Mexico_City", [6]string{"Central Standard Time", "CST", "Central Daylight Time", "CDT", "Central Time", "CT"}},
	{"America/Pangnirtung", [6]string{"Eastern Standard Time", "EST", "Eastern Daylight Time", "EDT", "Eastern Time", "ET"}},
	{"America/Porto_Velho", [6]string{"Amazon Standard Time", "", "Amazon Summer Time", "", "Amazon Time", ""}},
	{"America/Puerto_Rico", [6]string{"Atlantic Standard Time", "AST", "Atlantic Daylight Time", "ADT", "Atlantic Time", "AT"}},
	{"America/Rainy_River", [6]string{"Central Standard Time", "CST", "Central Daylight Time", "CDT", "Central Time", "CT"}},
	{"America/Tegucigalpa", [6]string{"Central Standard Time", "CST", "Central Daylight Time", "CDT", "Central Time", "CT"}},
	{"America/Thunder_Bay", [6]string{"Eastern Standard Time", "EST", "Eastern Daylight Time", "EDT", "Eastern Time", "ET"}},
	{"America/Yellowknife", [6]string{"Mountain Standard Time", "MST", "Mountain Daylight Time", "MDT", "Mountain Time", "MT"}},
	{"Arctic/Longyearbyen", [6]string{"Central European Standard Time", "", "Central European Summer Time", "", "Central European Time", ""}},
	{"Atlantic/Cape_Verde", [6]string{"Cape Verde Standard Time", "", "Cape Verde Summer Time", "", "Cape Verde Time", ""}},
	{"Australia/Lord_Howe", [6]string{"Lord Howe Standard Time", "", "Lord Howe Daylight Time", "", "Lord Howe Time", ""}},
	{"Australia/Melbourne", [6]string{"Australian Eastern Standard Time", "", "Australian Eastern Daylight Time", "", "Eastern Australia Time", ""}},
	{"Indian/Antananarivo", [6]string{"East Africa Time", "", "", "", "", ""}},
	{"Pacific/Guadalcanal", [6]string{"Solomon Islands Time", "", "", "", "", ""}},
	{"Africa/Dar_es_Salaam", [6]string{"East Africa Time", "", "", "", "", ""}},
	{"America/Blanc-Sablon", [6]string{"Atlantic Standard Time", "AST", "Atlantic Daylight Time", "ADT", "Atlantic Time", "AT"}},
	{"America/Buenos_Aires", [6]string{"Argentina Standard Time", "", "Argentina Summer Time", "", "Argentina Time", ""}},
	{"America/Campo_Grande", [6]string{"Amazon Standard Time", "", "Amazon Summer Time", "", "Amazon Time", ""}},
	{"America/Danmarkshavn", [6]string{"Greenwich Mean Time", "GMT", "", "", "", ""}},
	{"America/Dawson_Creek", [6]string{"Mountain Standard Time", "MST", "Mountain Daylight Time", "MDT", "Mountain Time", "MT"}},
	{"America/Indiana/Knox", [6]string{"Central Standard Time", "CST", "Central Daylight Time", "CDT", "Central Time", "CT"}},
	{"America/Rankin_Inlet", [6]string{"Central Standard Time", "CST", "Central Daylight Time", "CDT", "Central Time", "CT"}},
	{"America/Santa_Isabel", [6]string{"Northwest Mexico Standard Time", "", "Northwest Mexico Daylight Time", "", "Northwest Mexico Time", ""}},
	{"America/Scoresbysund", [6]string{"East Greenland Standard Time", "", "East Greenland Summer Time", "", "East Greenland Time", ""}},
	{"Antarctica/Macquarie", [6]string{"Australian Eastern Standard Time", "", "Australian Eastern Daylight Time", "", "Eastern Australia Time", ""}},
	{"Pacific/Port_Moresby", [6]string{"Papua New Guinea Time", "", "", "", "", ""}},
	{"America/Cambridge_Bay", [6]string{"Mountain Standard Time", "MST", "Mountain Daylight Time", "MDT", "Mountain Time", "MT"}},
	{"America/Ciudad_Juarez", [6]string{"Mountain Standard Time", "MST", "Mountain Daylight Time", "MDT", "Mountain Time", "MT"}},
	{"America/Coral_Harbour", [6]string{"Eastern Standard Time", "EST", "Eastern Daylight Time", "EDT", "Eastern Time", "ET"}},
	{"America/Indiana/Vevay", [6]string{"Eastern Standard Time", "EST", "Eastern Daylight Time", "EDT", "Eastern Time", "ET"}},
	{"America/Lower_Princes", [6]string{"Atlantic Standard Time", "AST", "Atlantic Daylight Time", "ADT", "Atlantic Time", "AT"}},
	{"America/Port_of_Spain", [6]string{"Atlantic Standard Time", "AST", "Atlantic Daylight Time", "ADT", "Atlantic Time", "AT"}},
	{"America/Santo_Domingo", [6]string{"Atlantic Standard Time", "AST", "Atlantic Daylight Time", "ADT", "Atlantic Time", "AT"}},
	{"America/St_Barthelemy", [6]string{"Atlantic Standard Time", "AST", "Atlantic Daylight Time", "ADT", "Atlantic Time", "AT"}},
	{"America/Swift_Current", [6]string{"Central Standard Time", "CST", "Central Daylight Time", "CDT", "Central Time", "CT"}},
	{"Antarctica/South_Pole", [6]string{"New Zealand Standard Time", "", "New Zealand Daylight Time", "", "New Zealand Time", ""}},
	{"Australia/Broken_Hill", [6]string{"Australian Central Standard Time", "", "Australian Central Daylight Time", "", "Central Australia Time", ""}},
	{"America/Bahia_Banderas", [6]string{"Central Standard Time", "CST", "Central Daylight Time", "CDT", "Central Time", "CT"}},
	{"America/Port-au-Prince", [6]string{"Eastern Standard Time", "EST", "Eastern Daylight Time", "EDT", "Eastern Time", "ET"}},
	{"Atlantic/South_Georgia", [6]string{"South Georgia Time", "", "", "", "", ""}},
	{"America/Argentina/Salta", [6]string{"Argentina Standard Time", "", "Argentina Summer Time", "", "Argentina Time", ""}},
	{"America/Indiana/Marengo", [6]string{"Eastern Standard Time", "EST", "Eastern Daylight Time", "EDT", "Eastern Time", "ET"}},
	{"America/Indiana/Winamac", [6]string{"Eastern Standard Time", "EST", "Eastern Daylight Time", "EDT", "Eastern Time", "ET"}},
	{"America/Argentina/Tucuman", [6]string{"Argentina Standard Time", "", "Argentina Summer Time", "", "Argentina Time", ""}},
	{"America/Argentina/Ushuaia", [6]string{"Argentina Standard Time", "", "Argentina Summer Time", "", "Argentina Time", ""}},
	{"America/Indiana/Tell_City", [6]string{"Central Standard Time", "CST", "Central Daylight Time", "CDT", "Central Time", "CT"}},
	{"America/Indiana/Vincennes", [6]string{"Eastern Standard Time", "EST", "Eastern Daylight Time", "EDT", "Eastern Time", "ET"}},
	{"Antarctica/DumontDUrville", [6]string{"Dumont-d’Urville Time", "", "", "", "", ""}},
	{"America/Argentina/La_Rioja", [6]string{"Argentina Standard Time", "", "Argentina Summer Time", "", "Argentina Time", ""}},
	{"America/Argentina/San_Juan", [6]string{"Argentina Standard Time", "", "Argentina Summer Time", "", "Argentina Time", ""}},
	{"America/Argentina/San_Luis", [6]string{"Argentina Standard Time", "", "Argentina Summer Time", "", "Argentina Time", ""}},
	{"America/Indiana/Petersburg", [6]string{"Eastern Standard Time", "EST", "Eastern Daylight Time", "EDT", "Eastern Time", "ET"}},
	{"America/Kentucky/Monticello", [6]string{"Eastern Standard Time", "EST", "Eastern Daylight Time", "EDT", "Eastern Time", "ET"}},
	{"America/North_Dakota/Beulah", [6]string{"Central Standard Time", "CST", "Central Daylight Time", "CDT", "Central Time", "CT"}},
	{"America/North_Dakota/Center", [6]string{"Central Standard Time", "CST", "Central Daylight Time", "CDT", "Central Time", "CT"}},
	{"America/Argentina/Rio_Gallegos", [6]string{"Argentina Standard Time", "", "Argentina Summer Time", "", "Argentina Time", ""}},
	{"America/North_Dakota/New_Salem", [6]string{"Central Standard Time", "CST", "Central Daylight Time", "CDT", "Central Time", "CT"}},
}
