#!/usr/bin/env python3
# Copyright (c) 2001, 2023, Oracle and/or its affiliates (reference algorithm).
# Derived from pinned OpenJDK GenerateCurrencyData.java; original reference
# source and notices are retained under stdjava/testdata/currency_jdk21_177.
# GNU General Public License version 2 only with the Classpath exception;
# see stdjava/testdata/currency_jdk21_177/LICENSE.
# This deterministic generator reads public platform data, never JVM outputs.
from pathlib import Path
from datetime import datetime, timezone
import hashlib
import json
import struct
import argparse
parser = argparse.ArgumentParser()
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
repo = Path(__file__).resolve().parents[1]
properties_file = repo / 'stdjava/testdata/currency_jdk21_177/CurrencyData.properties'
assert hashlib.sha256(properties_file.read_bytes()).hexdigest() == '070dfbffa4fb770776cd481f8a6b682e39192b0ceb343ee89c363c518c69b27c'
props = {}
pending = ''
for physical in properties_file.read_text(encoding='utf-8').splitlines():
    line = pending + physical.lstrip()
    if line.endswith('\\'):
        pending = line[:-1]
        continue
    pending = ''
    if not line or line[0] in '#!':
        continue
    key, value = line.split('=', 1)
    assert key not in props
    assert '\\' not in value  # relevant pinned values are ASCII, not escapes
    props[key.strip()] = value.strip()
assert not pending
assert props['formatVersion'] == '3' and props['dataVersion'] == '177'
all_codes = props['all'].split('-')
assert all(len(code) == 6 and code[:3].isupper() and code[3:].isdigit() for code in all_codes)
numeric = {code[:3]: int(code[3:]) for code in all_codes}
assert len(numeric) == len(all_codes)

def digits(code):
    for i in range(10):
        if code in props.get('minor' + str(i), ''):
            return i
    return -1 if code in props['minorUndefined'] else 2

main = []
special = []
by_info = {}
for first in range(26):
    for second in range(26):
        country = chr(65 + first) + chr(65 + second)
        info = props.get(country)
        if info is None:
            entry = 0x7f
        elif not info:
            entry = 0x200
        elif len(info) == 3 and info[:2] == country:
            assert info in numeric and 0 <= digits(info) <= 9
            entry = ord(info[2]) - 65 | digits(info) << 5 | numeric[info] << 10
        else:
            if info not in by_info:
                if len(info) == 3:
                    old, new, cutover = info, '', (1 << 63) - 1
                else:
                    old, stamp, new = info.split(';')
                    cutover = int(datetime.strptime(stamp, '%Y-%m-%d-%H-%M-%S').replace(tzinfo=timezone.utc).timestamp() * 1000)
                assert old in numeric and (not new or new in numeric)
                by_info[info] = len(special)
                special.append((cutover, old, new, digits(old), digits(new) if new else 0, numeric[old], numeric[new] if new else 0))
            entry = 0x200 | by_info[info] + 1
        main.append(entry)

future = {row[2] for row in special}
other = []
for item in all_codes:
    code = item[:3]
    entry = main[(ord(code[0]) - 65) * 26 + ord(code[1]) - 65]
    if code not in future and entry & 31 != ord(code[2]) - 65:
        other.append((code, digits(code), numeric[code]))
assert (len(main), len(special), len(other)) == (676, 15, 80)

def utf(value):
    raw = value.encode('ascii')
    return struct.pack('>H', len(raw)) + raw

main_bytes = struct.pack('>676I', *main)
special_bytes = b''.join(struct.pack('>q', row[0]) + utf(row[1]) + utf(row[2]) + struct.pack('>4i', *row[3:]) for row in special)
other_bytes = b''.join(utf(code) + struct.pack('>2i', frac, number) for code, frac, number in other)
public_binary = struct.pack('>3I', 0x43757244, 3, 177) + main_bytes + struct.pack('>I', len(special)) + special_bytes + struct.pack('>I', len(other)) + other_bytes


assert hashlib.sha256(public_binary).hexdigest() == '83c35f47bdc9406f7b15768ff48f88176e69933f778ea141f0433b41f07db343'
lines = ["// Code generated by tools/generate-currency-data.py; DO NOT EDIT.",
 "// Derived from OpenJDK jdk21u jdk-21.0.6+7 CurrencyData.properties.",
 "// Copyright (c) 2000, 2024, Oracle and/or its affiliates.",
 "// GPL version 2 only with the Classpath exception; see testdata/currency_jdk21_177/LICENSE.",
 "// Public input SHA256 070dfbffa4fb770776cd481f8a6b682e39192b0ceb343ee89c363c518c69b27c.",
 "// Complete format3/revision177 resource SHA256 83c35f47bdc9406f7b15768ff48f88176e69933f778ea141f0433b41f07db343.",
 "package stdjava", "", "var currencyMainTable = [...]uint32{"]
for entry in main: lines.append("\t0x%08x," % entry)
lines.extend(["}", "", "var currencySpecialCases = [...]currencySpecialCase{"])
for cutover, old, new, ofrac, nfrac, onum, nnum in special:
 lines.append("\t{%d, %s, %s, %d, %d, %d, %d}," % (cutover, json.dumps(old), json.dumps(new), ofrac, nfrac, onum, nnum))
lines.extend(["}", "", "var currencyOtherCodes = [...]currencyOtherCode{"])
for code, fraction, number in other: lines.append("\t{%s, %d, %d}," % (json.dumps(code), fraction, number))
lines.extend(["}", ""])
output = ("\n".join(lines)).encode()
destination = repo / 'stdjava/currency_data.go'
if args.check:
 assert destination.read_bytes() == output, 'currency data is not the pinned deterministic generation'
else: destination.write_bytes(output)
